name: quarkus-ex
servicePort: 8080

image:
  name: quay.io/mcanoy/quarkus-ex
  tag: latest

cleanupJob:
  image:
    name: quay.io/redhat-cop/gitlab-cleanup
    tag: v3.11.6
  ref: master
  env:
    logLevel: DEBUG
    deleteAfterInHours: 1
    dryRun: false
    gitlabApiUrl: xxxxx
    parentGroupId: 7775
    gitlabToken: xxxxx
    githubToken: xxxxx
    githubApiUrl: https://api.github.com/repos/mcanoy/quarkus-ex/actions/workflows/checkout-ex.yml/dispatches
  
exampleJob:
  image:
    name: quay.io/mcanoy/quarkus-ex
    tag: latest

secrets:
  name: quarkus-ex-secrets
  one: two
  three: four
configMap:
  name: example-cm
space: https://outer
