name: cypress-test

on:
  push:
     branches:
       - master

jobs:
  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rht-labs/lodestar-frontend
      - name: end-to-end test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          env: baseUrl=https://lodestar.rht-labs.com
