name: cypress-test

on:
  push:
     branches:
       - master

jobs:
  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rht-labs/lodestar-frontend
      - name: end-to-end test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
          env: SSO_URL=${{ secrets.CYPRESS_SSO_URL }},SSO_USER=${{ secrets.CYPRESS_SSO_USER }},SSO_PASSWORD=${{ CYPRESS_SSO_PASSWORD}}
