on:
  push:
     branches:
       - master

jobs:
  checkout-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: rht-labs/lodestar-frontend
        path: testing
