name: cypress-test

on: 
  workflow_dispatch:
    inputs:
      cypressTag:
        description: "tag for cypress dashboard"
        default: "mcanoy"       
      tags:
        description: "End-to-End Test Run"

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rht-labs/lodestar-frontend
      - name: end-to-end test
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: true
          tag: ${{ github.event.inputs.cypressTag }} 
          config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
          env: SSO_URL=${{ secrets.CYPRESS_SSO_URL }},SSO_USER=${{ secrets.CYPRESS_SSO_USER }},SSO_PASSWORD=${{ secrets.CYPRESS_SSO_PASSWORD}},SSO_CLIENT_ID=${{ secrets.CYPRESS_SSO_CLIENT_ID }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: print dashboard url
        if: always()
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
