name: what-does-my-secret-look-like

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: "bEnd-to-bEnd Test Run"

jobs:
  bend-to-bend:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      run: |
        if [[ "parta!partb$bparc" == "$SUPER_SECRET" ]]; then echo true; else echo false; fi
        echo ${#SUPER_SECRET}
        if [[ $SUPER_SECRET == parta!partb$parc* ]]; then echo true; else echo false; fi
        ANOTHER=${SUPER_SECRET#?};
        echo "$ANOTHER"
