name: Publish Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        find: "###VERSION###"
        replace: "${{ github.sha }}"
        include: ".s2i"
    - name: Build with Maven & Quarkus
      run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=true org.jacoco:jacoco-maven-plugin:report
    - uses: redhat-cop/github-actions/s2i@v2
      with:
        base: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.8
        output_image: "quay.io/mcanoy/quarkus-ex:${{ github.sha }}"
        image_push_registry: quay.io
        image_push_username: ${{ secrets.QUAY_USERNAME }}
        image_push_password: ${{ secrets.QUAY_PASSWORD }}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: target/site/jacoco
